// ============================================================
// PULSEGRID — PERMISSION KEYS (enum-like constants)
// ============================================================
export const Permission = {
  // User management
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_USERS: 'VIEW_USERS',
  APPROVE_USERS: 'APPROVE_USERS',
  ASSIGN_ROLES: 'ASSIGN_ROLES',
  // Hospital management
  MANAGE_HOSPITALS: 'MANAGE_HOSPITALS',
  VIEW_HOSPITALS: 'VIEW_HOSPITALS',
  MANAGE_HOSPITAL_STAFF: 'MANAGE_HOSPITAL_STAFF',
  // Patient management
  VIEW_PATIENTS: 'VIEW_PATIENTS',
  MANAGE_PATIENTS: 'MANAGE_PATIENTS',
  VIEW_OWN_PROFILE: 'VIEW_OWN_PROFILE',
  EDIT_OWN_PROFILE: 'EDIT_OWN_PROFILE',
  // Medical records
  READ_MEDICAL_RECORDS: 'READ_MEDICAL_RECORDS',
  WRITE_MEDICAL_RECORDS: 'WRITE_MEDICAL_RECORDS',
  DELETE_MEDICAL_RECORDS: 'DELETE_MEDICAL_RECORDS',
  // Prescriptions
  WRITE_PRESCRIPTION: 'WRITE_PRESCRIPTION',
  READ_PRESCRIPTION: 'READ_PRESCRIPTION',
  DISPENSE_MEDICATION: 'DISPENSE_MEDICATION',
  // Diagnostics
  ORDER_DIAGNOSTICS: 'ORDER_DIAGNOSTICS',
  VIEW_DIAGNOSTICS: 'VIEW_DIAGNOSTICS',
  UPLOAD_DIAGNOSTIC_RESULTS: 'UPLOAD_DIAGNOSTIC_RESULTS',
  // Emergency
  TRIGGER_EMERGENCY: 'TRIGGER_EMERGENCY',
  RESPOND_EMERGENCY: 'RESPOND_EMERGENCY',
  MANAGE_AMBULANCE: 'MANAGE_AMBULANCE',
  VIEW_EMERGENCY_REQUESTS: 'VIEW_EMERGENCY_REQUESTS',
  // Notifications
  SEND_NOTIFICATIONS: 'SEND_NOTIFICATIONS',
  VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS',
  BROADCAST_ALERTS: 'BROADCAST_ALERTS',
  // Audit
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  EXPORT_AUDIT_LOGS: 'EXPORT_AUDIT_LOGS',
  // Analytics
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_ADVANCED_ANALYTICS: 'VIEW_ADVANCED_ANALYTICS',
  // Settings
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  // Family
  VIEW_FAMILY_MEMBER_RECORDS: 'VIEW_FAMILY_MEMBER_RECORDS',
  MANAGE_FAMILY_LINKS: 'MANAGE_FAMILY_LINKS',
} as const;

export type PermissionKey = (typeof Permission)[keyof typeof Permission];
